// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock_bookmark

import (
	context "context"

	model "github.com/HemlockPham7/worker-service/internal/app/model"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreateBatchBookmarks provides a mock function with given fields: ctx, bookmarks
func (_m *Repository) CreateBatchBookmarks(ctx context.Context, bookmarks []*model.Bookmark) error {
	ret := _m.Called(ctx, bookmarks)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatchBookmarks")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*model.Bookmark) error); ok {
		r0 = rf(ctx, bookmarks)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
