// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock_bookmark

import (
	context "context"

	queue "github.com/HemlockPham7/worker-service/internal/app/service/queue"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CreateBatchBookmarks provides a mock function with given fields: ctx, userId, bookmarkList
func (_m *Service) CreateBatchBookmarks(ctx context.Context, userId string, bookmarkList []*queue.ImportBookmarkInput) error {
	ret := _m.Called(ctx, userId, bookmarkList)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatchBookmarks")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []*queue.ImportBookmarkInput) error); ok {
		r0 = rf(ctx, userId, bookmarkList)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
